I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gui.rpy", line 91, in script
    define gui.main_menu_background = Movie(play)
  File "game/gui.rpy", line 91, in script
    define gui.main_menu_background = Movie(play)
  File "game/gui.rpy", line 91, in <module>
    define gui.main_menu_background = Movie(play)
NameError: name 'play' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\EDUSERVICES\Desktop\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\EDUSERVICES\Desktop\renpy-8.3.4-sdk\renpy\main.py", line 541, in main
    renpy.game.context().run(node)
  File "game/gui.rpy", line 91, in script
    define gui.main_menu_background = Movie(play)
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/gui.rpy", line 91, in script
    define gui.main_menu_background = Movie(play)
  File "D:\EDUSERVICES\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2241, in execute
    self.set()
  File "D:\EDUSERVICES\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2255, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\EDUSERVICES\Desktop\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/gui.rpy", line 91, in <module>
    define gui.main_menu_background = Movie(play)
NameError: name 'play' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
VisualNovelProject 1.0
Wed Feb 19 13:34:26 2025
