I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 464, in script
    jump afterFight  # Fin du combat
ScriptError: could not find label 'afterFight'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 464, in script
    jump afterFight  # Fin du combat
  File "C:\Users\evanl\OneDrive\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\evanl\OneDrive\Desktop\renpy-8.3.4-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'afterFight'.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
Develop Through Hardship 1.0
Wed Mar 12 01:39:49 2025
